<?php

use Faker\Factory as Faker;
use TeenQuotes\Countries\Models\Country;

class CountriesTableSeeder extends Seeder {

	public function run()
	{
		$this->command->info('Deleting existing Countries table ...');
		Country::truncate();

		$this->command->info('Seeding Countries table');

		Country::create(['name' => 'Afghanistan', 'country_code' => 'AF']);
		Country::create(['name' => 'Albania', 'country_code' => 'AL']);
		Country::create(['name' => 'Algeria', 'country_code' => 'DZ']);
		Country::create(['name' => 'American Samoa', 'country_code' => 'AS']);
		Country::create(['name' => 'Andorra', 'country_code' => 'AD']);
		Country::create(['name' => 'Angola', 'country_code' => 'AO']);
		Country::create(['name' => 'Anguilla', 'country_code' => 'AI']);
		Country::create(['name' => 'Antarctica', 'country_code' => 'AQ']);
		Country::create(['name' => 'Antigua and Barbuda', 'country_code' => 'AG']);
		Country::create(['name' => 'Argentina', 'country_code' => 'AR']);
		Country::create(['name' => 'Armenia', 'country_code' => 'AM']);
		Country::create(['name' => 'Aruba', 'country_code' => 'AW']);
		Country::create(['name' => 'Australia', 'country_code' => 'AU']);
		Country::create(['name' => 'Austria', 'country_code' => 'AT']);
		Country::create(['name' => 'Azerbaijan', 'country_code' => 'AZ']);
		Country::create(['name' => 'Bahamas', 'country_code' => 'BS']);
		Country::create(['name' => 'Bahrain', 'country_code' => 'BH']);
		Country::create(['name' => 'Bangladesh', 'country_code' => 'BD']);
		Country::create(['name' => 'Barbados', 'country_code' => 'BB']);
		Country::create(['name' => 'Belarus', 'country_code' => 'BY']);
		Country::create(['name' => 'Belgium', 'country_code' => 'BE']);
		Country::create(['name' => 'Belize', 'country_code' => 'BZ']);
		Country::create(['name' => 'Benin', 'country_code' => 'BJ']);
		Country::create(['name' => 'Bermuda', 'country_code' => 'BM']);
		Country::create(['name' => 'Bhutan', 'country_code' => 'BT']);
		Country::create(['name' => 'Bolivia', 'country_code' => 'BO']);
		Country::create(['name' => 'Bosnia and Herzegovina', 'country_code' => 'BA']);
		Country::create(['name' => 'Botswana', 'country_code' => 'BW']);
		Country::create(['name' => 'Bouvet Island', 'country_code' => 'BV']);
		Country::create(['name' => 'Brazil', 'country_code' => 'BR']);
		Country::create(['name' => 'British Indian Ocean Territory', 'country_code' => 'IO']);
		Country::create(['name' => 'Brunei Darussalam', 'country_code' => 'BN']);
		Country::create(['name' => 'Bulgaria', 'country_code' => 'BG']);
		Country::create(['name' => 'Burkina Faso', 'country_code' => 'BF']);
		Country::create(['name' => 'Burundi', 'country_code' => 'BI']);
		Country::create(['name' => 'Cambodia', 'country_code' => 'KH']);
		Country::create(['name' => 'Cameroon', 'country_code' => 'CM']);
		Country::create(['name' => 'Canada', 'country_code' => 'CA']);
		Country::create(['name' => 'Cape Verde', 'country_code' => 'CV']);
		Country::create(['name' => 'Cayman Islands', 'country_code' => 'KY']);
		Country::create(['name' => 'Central African Republic', 'country_code' => 'CF']);
		Country::create(['name' => 'Chad', 'country_code' => 'TD']);
		Country::create(['name' => 'Chile', 'country_code' => 'CL']);
		Country::create(['name' => 'China', 'country_code' => 'CN']);
		Country::create(['name' => 'Christmas Island', 'country_code' => 'CX']);
		Country::create(['name' => 'Cocos (Keeling) Islands', 'country_code' => 'CC']);
		Country::create(['name' => 'Colombia', 'country_code' => 'CO']);
		Country::create(['name' => 'Comoros', 'country_code' => 'KM']);
		Country::create(['name' => 'Congo', 'country_code' => 'CG']);
		Country::create(['name' => 'Congo The Democratic Republic of The Congo', 'country_code' => 'CD']);
		Country::create(['name' => 'Cook Islands', 'country_code' => 'CK']);
		Country::create(['name' => 'Costa Rica', 'country_code' => 'CR']);
		Country::create(['name' => 'Cote D\'ivoire', 'country_code' => 'CI']);
		Country::create(['name' => 'Croatia', 'country_code' => 'HR']);
		Country::create(['name' => 'Cuba', 'country_code' => 'CU']);
		Country::create(['name' => 'Cyprus', 'country_code' => 'CY']);
		Country::create(['name' => 'Czech Republic', 'country_code' => 'CZ']);
		Country::create(['name' => 'Denmark', 'country_code' => 'DK']);
		Country::create(['name' => 'Djibouti', 'country_code' => 'DJ']);
		Country::create(['name' => 'Dominica', 'country_code' => 'DM']);
		Country::create(['name' => 'Dominican Republic', 'country_code' => 'DO']);
		Country::create(['name' => 'Ecuador', 'country_code' => 'EC']);
		Country::create(['name' => 'Egypt', 'country_code' => 'EG']);
		Country::create(['name' => 'El Salvador', 'country_code' => 'SV']);
		Country::create(['name' => 'Equatorial', 'country_code' => 'GQ']);
		Country::create(['name' => 'Eritrea', 'country_code' => 'ER']);
		Country::create(['name' => 'Estonia', 'country_code' => 'EE']);
		Country::create(['name' => 'Ethiopia', 'country_code' => 'ET']);
		Country::create(['name' => 'Falkland Islands (Malvinas)', 'country_code' => 'FK']);
		Country::create(['name' => 'Faroe', 'country_code' => 'FO']);
		Country::create(['name' => 'Fiji', 'country_code' => 'FJ']);
		Country::create(['name' => 'Finland', 'country_code' => 'FI']);
		Country::create(['name' => 'France', 'country_code' => 'FR']);
		Country::create(['name' => 'French Guiana', 'country_code' => 'GF']);
		Country::create(['name' => 'French Polynesia', 'country_code' => 'PF']);
		Country::create(['name' => 'French Southern Territories', 'country_code' => 'TF']);
		Country::create(['name' => 'Gabon', 'country_code' => 'GA']);
		Country::create(['name' => 'Gambia', 'country_code' => 'GM']);
		Country::create(['name' => 'Georgia', 'country_code' => 'GE']);
		Country::create(['name' => 'Germany', 'country_code' => 'DE']);
		Country::create(['name' => 'Ghana', 'country_code' => 'GH']);
		Country::create(['name' => 'Gibraltar', 'country_code' => 'GI']);
		Country::create(['name' => 'Greece', 'country_code' => 'GR']);
		Country::create(['name' => 'Greenland', 'country_code' => 'GL']);
		Country::create(['name' => 'Grenada', 'country_code' => 'GD']);
		Country::create(['name' => 'Guadeloupe', 'country_code' => 'GP']);
		Country::create(['name' => 'Guam', 'country_code' => 'GU']);
		Country::create(['name' => 'Guatemala', 'country_code' => 'GT']);
		Country::create(['name' => 'Guinea', 'country_code' => 'GN']);
		Country::create(['name' => 'Guinea-Bissau', 'country_code' => 'GW']);
		Country::create(['name' => 'Guyana', 'country_code' => 'GY']);
		Country::create(['name' => 'Haiti', 'country_code' => 'HT']);
		Country::create(['name' => 'Heard Island and McDonald Islands', 'country_code' => 'HM']);
		Country::create(['name' => 'Honduras', 'country_code' => 'HN']);
		Country::create(['name' => 'Hong Kong', 'country_code' => 'HK']);
		Country::create(['name' => 'Hungary', 'country_code' => 'HU']);
		Country::create(['name' => 'Iceland', 'country_code' => 'IS']);
		Country::create(['name' => 'India', 'country_code' => 'IN']);
		Country::create(['name' => 'Indonesia', 'country_code' => 'ID']);
		Country::create(['name' => 'Iran', 'country_code' => 'IR']);
		Country::create(['name' => 'Iraq', 'country_code' => 'IQ']);
		Country::create(['name' => 'Ireland', 'country_code' => 'IE']);
		Country::create(['name' => 'Israel', 'country_code' => 'IL']);
		Country::create(['name' => 'Italy', 'country_code' => 'IT']);
		Country::create(['name' => 'Jamaica', 'country_code' => 'JM']);
		Country::create(['name' => 'Japan', 'country_code' => 'JP']);
		Country::create(['name' => 'Jordan', 'country_code' => 'JO']);
		Country::create(['name' => 'Kazakhstan', 'country_code' => 'KZ']);
		Country::create(['name' => 'Kenya', 'country_code' => 'KE']);
		Country::create(['name' => 'Kiribati', 'country_code' => 'KI']);
		Country::create(['name' => 'Korea', 'country_code' => 'KR']);
		Country::create(['name' => 'Kuwait', 'country_code' => 'KW']);
		Country::create(['name' => 'Kyrgyzstan', 'country_code' => 'KG']);
		Country::create(['name' => 'Lao People\'s Democratic Republic', 'country_code' => 'LA']);
		Country::create(['name' => 'Latvia', 'country_code' => 'LV']);
		Country::create(['name' => 'Lebanon', 'country_code' => 'LB']);
		Country::create(['name' => 'Lesotho', 'country_code' => 'LS']);
		Country::create(['name' => 'Liberia', 'country_code' => 'LR']);
		Country::create(['name' => 'Libyan Arab Jamahiriya', 'country_code' => 'LY']);
		Country::create(['name' => 'Liechtenstein', 'country_code' => 'LI']);
		Country::create(['name' => 'Lithuania', 'country_code' => 'LT']);
		Country::create(['name' => 'Luxembourg', 'country_code' => 'LU']);
		Country::create(['name' => 'Macao', 'country_code' => 'MO']);
		Country::create(['name' => 'Macedonia', 'country_code' => 'MK']);
		Country::create(['name' => 'Madagascar', 'country_code' => 'MG']);
		Country::create(['name' => 'Malawi', 'country_code' => 'MW']);
		Country::create(['name' => 'Malaysia', 'country_code' => 'MY']);
		Country::create(['name' => 'Maldives', 'country_code' => 'MV']);
		Country::create(['name' => 'Mali', 'country_code' => 'ML']);
		Country::create(['name' => 'Malta', 'country_code' => 'MT']);
		Country::create(['name' => 'Marshall Islands', 'country_code' => 'MH']);
		Country::create(['name' => 'Martinique', 'country_code' => 'MQ']);
		Country::create(['name' => 'Mauritania', 'country_code' => 'MR']);
		Country::create(['name' => 'Mauritius', 'country_code' => 'MU']);
		Country::create(['name' => 'Mayotte', 'country_code' => 'YT']);
		Country::create(['name' => 'Mexico', 'country_code' => 'MX']);
		Country::create(['name' => 'Micronesia', 'country_code' => 'FM']);
		Country::create(['name' => 'Moldova', 'country_code' => 'MD']);
		Country::create(['name' => 'Monaco', 'country_code' => 'MC']);
		Country::create(['name' => 'Mongolia', 'country_code' => 'MN']);
		Country::create(['name' => 'Montserrat', 'country_code' => 'MS']);
		Country::create(['name' => 'Morocco', 'country_code' => 'MA']);
		Country::create(['name' => 'Mozambique', 'country_code' => 'MZ']);
		Country::create(['name' => 'Myanmar', 'country_code' => 'MM']);
		Country::create(['name' => 'Namibia', 'country_code' => 'NA']);
		Country::create(['name' => 'Nauru', 'country_code' => 'NR']);
		Country::create(['name' => 'Nepal', 'country_code' => 'NP']);
		Country::create(['name' => 'Netherlands', 'country_code' => 'NL']);
		Country::create(['name' => 'Netherlands Antilles', 'country_code' => 'BQ']);
		Country::create(['name' => 'New Caledonia', 'country_code' => 'NC']);
		Country::create(['name' => 'New Zealand', 'country_code' => 'NZ']);
		Country::create(['name' => 'Nicaragua', 'country_code' => 'NI']);
		Country::create(['name' => 'Niger', 'country_code' => 'NE']);
		Country::create(['name' => 'Nigeria', 'country_code' => 'NG']);
		Country::create(['name' => 'Niue', 'country_code' => 'NU']);
		Country::create(['name' => 'Norfolk Island', 'country_code' => 'NF']);
		Country::create(['name' => 'Northern Mariana Islands', 'country_code' => 'MP']);
		Country::create(['name' => 'Norway', 'country_code' => 'NO']);
		Country::create(['name' => 'Oman', 'country_code' => 'OM']);
		Country::create(['name' => 'Pakistan', 'country_code' => 'PK']);
		Country::create(['name' => 'Palau', 'country_code' => 'PW']);
		Country::create(['name' => 'Palestinian Territory', 'country_code' => 'PS']);
		Country::create(['name' => 'Panama', 'country_code' => 'PA']);
		Country::create(['name' => 'Papua New Guinea', 'country_code' => 'PG']);
		Country::create(['name' => 'Paraguay', 'country_code' => 'PY']);
		Country::create(['name' => 'Peru', 'country_code' => 'PE']);
		Country::create(['name' => 'Philippines', 'country_code' => 'PH']);
		Country::create(['name' => 'Pitcairn', 'country_code' => 'PN']);
		Country::create(['name' => 'Poland', 'country_code' => 'PL']);
		Country::create(['name' => 'Portugal', 'country_code' => 'PT']);
		Country::create(['name' => 'Puerto Rico', 'country_code' => 'PR']);
		Country::create(['name' => 'Qatar', 'country_code' => 'QA']);
		Country::create(['name' => 'Reunion', 'country_code' => 'RE']);
		Country::create(['name' => 'Romania', 'country_code' => 'RO']);
		Country::create(['name' => 'Russian Federation', 'country_code' => 'RU']);
		Country::create(['name' => 'Rwanda', 'country_code' => 'RW']);
		Country::create(['name' => 'Saint Helena', 'country_code' => 'SH']);
		Country::create(['name' => 'Saint Kitts and Nevis', 'country_code' => 'KN']);
		Country::create(['name' => 'Saint Lucia', 'country_code' => 'LC']);
		Country::create(['name' => 'Saint Pierre and Miquelon', 'country_code' => 'PM']);
		Country::create(['name' => 'Saint Vincent and the Grenadines', 'country_code' => 'VC']);
		Country::create(['name' => 'Samoa', 'country_code' => 'WS']);
		Country::create(['name' => 'San Marino', 'country_code' => 'SM']);
		Country::create(['name' => 'Sao Tome and Principe', 'country_code' => 'ST']);
		Country::create(['name' => 'Saudi Arabia', 'country_code' => 'SA']);
		Country::create(['name' => 'Senegal', 'country_code' => 'SN']);
		Country::create(['name' => 'Serbia', 'country_code' => 'RS']);
		Country::create(['name' => 'Seychelles', 'country_code' => 'SC']);
		Country::create(['name' => 'Sierra Leone', 'country_code' => 'SL']);
		Country::create(['name' => 'Singapore', 'country_code' => 'SG']);
		Country::create(['name' => 'Slovakia', 'country_code' => 'Sk']);
		Country::create(['name' => 'Slovenia', 'country_code' => 'SI']);
		Country::create(['name' => 'Solomon Islands', 'country_code' => 'SB']);
		Country::create(['name' => 'Somalia', 'country_code' => 'SO']);
		Country::create(['name' => 'South Africa', 'country_code' => 'ZA']);
		Country::create(['name' => 'South Georgia and The South Sandwich Islands', 'country_code' => 'GS']);
		Country::create(['name' => 'Spain', 'country_code' => 'ES']);
		Country::create(['name' => 'Sri Lanka', 'country_code' => 'LK']);
		Country::create(['name' => 'Sudan', 'country_code' => 'SD']);
		Country::create(['name' => 'Suriname', 'country_code' => 'SR']);
		Country::create(['name' => 'Svalbard and Jan Mayen', 'country_code' => 'SJ']);
		Country::create(['name' => 'Swaziland', 'country_code' => 'SZ']);
		Country::create(['name' => 'Sweden', 'country_code' => 'SE']);
		Country::create(['name' => 'Switzerland', 'country_code' => 'CH']);
		Country::create(['name' => 'Syrian Arab Republic', 'country_code' => 'SY']);
		Country::create(['name' => 'Taiwan', 'country_code' => 'TW']);
		Country::create(['name' => 'Tajikistan', 'country_code' => 'TJ']);
		Country::create(['name' => 'Tanzania', 'country_code' => 'TZ']);
		Country::create(['name' => 'Thailand', 'country_code' => 'TH']);
		Country::create(['name' => 'Timor-leste', 'country_code' => 'TL']);
		Country::create(['name' => 'Togo', 'country_code' => 'TG']);
		Country::create(['name' => 'Tokelau', 'country_code' => 'TK']);
		Country::create(['name' => 'Tonga', 'country_code' => 'TO']);
		Country::create(['name' => 'Trinidad and Tobago', 'country_code' => 'TT']);
		Country::create(['name' => 'Tunisia', 'country_code' => 'TN']);
		Country::create(['name' => 'Turkey', 'country_code' => 'TR']);
		Country::create(['name' => 'Turkmenistan', 'country_code' => 'TM']);
		Country::create(['name' => 'Turks and Caicos Islands', 'country_code' => 'TC']);
		Country::create(['name' => 'Tuvalu', 'country_code' => 'TV']);
		Country::create(['name' => 'Uganda', 'country_code' => 'UG']);
		Country::create(['name' => 'Ukraine', 'country_code' => 'UA']);
		Country::create(['name' => 'United Arab Emirates', 'country_code' => 'AE']);
		Country::create(['name' => 'United Kingdom', 'country_code' => 'GB']);
		Country::create(['name' => 'United States', 'country_code' => 'US']);
		Country::create(['name' => 'United States Minor Outlying Islands', 'country_code' => 'UM']);
		Country::create(['name' => 'Uruguay', 'country_code' => 'UY']);
		Country::create(['name' => 'Uzbekistan', 'country_code' => 'UZ']);
		Country::create(['name' => 'Vanuatu', 'country_code' => 'VU']);
		Country::create(['name' => 'Venezuela', 'country_code' => 'VE']);
		Country::create(['name' => 'Vietnam', 'country_code' => 'VN']);
		Country::create(['name' => 'Virgin Islands, British Virgin Islands', 'country_code' => 'VG']);
		Country::create(['name' => 'Virgin Islands, U.S. Virgin Islands', 'country_code' => 'VI']);
		Country::create(['name' => 'Wallis and Futuna', 'country_code' => 'WF']);
		Country::create(['name' => 'Western Sahara', 'country_code' => 'EH']);
		Country::create(['name' => 'Yemen', 'country_code' => 'YE']);
		Country::create(['name' => 'Zambia', 'country_code' => 'ZM']);
		Country::create(['name' => 'Zimbabwe', 'country_code' => 'ZW']);
	}
}